<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_May 19, 2022_attachment-medium size-med_469064</name>
   <tag></tag>
   <elementGuidId>ad683bba-5d44-43b4-a7ed-2ad51a28f9d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-medium.size-medium.wp-image-965</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value> </value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>af805e66-64bb-4e95-a153-8fc758c0575b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>a83cc211-6bee-45c1-a729-f988acee2c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a02973f0-3a8e-47b7-93d9-d1ace9b8c362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>d2521ef9-0dbe-4115-9062-a8d7b6ef002d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>7de6430e-73bb-43d1-9283-502dcfb7306c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/absolutvision-UudGNHJdNSo-unsplash-scaled-1-300x200.jpg</value>
      <webElementGuid>5f23e3bf-96ff-4ccb-bc1f-2447c20175e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-medium size-medium wp-image-965</value>
      <webElementGuid>209202d3-9ee0-4ed5-9b27-19ccb7c9b9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/absolutvision-UudGNHJdNSo-unsplash-scaled-1-300x200.jpg 300w, http://3.145.59.133:8202/wp-content/uploads/2023/12/absolutvision-UudGNHJdNSo-unsplash-scaled-1-1024x683.jpg 1024w, http://3.145.59.133:8202/wp-content/uploads/2023/12/absolutvision-UudGNHJdNSo-unsplash-scaled-1-768x512.jpg 768w, http://3.145.59.133:8202/wp-content/uploads/2023/12/absolutvision-UudGNHJdNSo-unsplash-scaled-1-1536x1024.jpg 1536w, http://3.145.59.133:8202/wp-content/uploads/2023/12/absolutvision-UudGNHJdNSo-unsplash-scaled-1-2048x1366.jpg 2048w</value>
      <webElementGuid>2fed3f3f-6d69-42af-a5f7-547a09d68a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>3a76f976-09c8-4eb1-b073-4ac05d1dcbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-213 page-child parent-pageid-203 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-213 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-213&quot;]/div[@class=&quot;elementor-element elementor-element-71ab9126 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-365d7baa elementor-grid-3 elementor-grid-tablet-2 elementor-grid-mobile-1 elementor-posts--thumbnail-top elementor-widget elementor-widget-posts&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-posts-container elementor-posts elementor-posts--skin-classic elementor-grid elementor-has-item-ratio&quot;]/article[@class=&quot;elementor-post elementor-grid-item post-964 post type-post status-publish format-standard has-post-thumbnail hentry category-accessibility-testing&quot;]/a[@class=&quot;elementor-post__thumbnail__link&quot;]/div[@class=&quot;elementor-post__thumbnail&quot;]/img[@class=&quot;attachment-medium size-medium wp-image-965&quot;]</value>
      <webElementGuid>5939e655-c601-48ce-9582-f0d862d7f3ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/absolutvision-UudGNHJdNSo-unsplash-scaled-1-300x200.jpg')]</value>
      <webElementGuid>e14dacba-5782-49a2-895a-4671f6e2ea07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[3]/a/div/img</value>
      <webElementGuid>0ca4321e-07e6-413d-ac6c-44d9a351d6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/2023/12/absolutvision-UudGNHJdNSo-unsplash-scaled-1-300x200.jpg']</value>
      <webElementGuid>89c67066-4df8-43a5-b510-fb9dbfccc794</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
