<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Learn more about accessibility testing__2dc4f4</name>
   <tag></tag>
   <elementGuidId>f45ccba3-89bc-4cc8-9d09-bf2d340db755</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-medium.size-medium.wp-image-460</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/Enterprise-300x158.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8ad4fe0e-17cf-49ca-b92f-460fa01bad4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>4dd4f749-a4c1-4030-802b-5d74d58df07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>2ce64cbe-a675-4dda-b7f0-5fa23216cb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>0b374470-6014-4fcc-b221-d84dad3a0896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>158</value>
      <webElementGuid>acaccfd4-c68e-49ce-819d-90f2cf7bed42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/Enterprise-300x158.png</value>
      <webElementGuid>3eaa5077-5f50-4d48-95d9-7631fc0a90ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-medium size-medium wp-image-460</value>
      <webElementGuid>1b1fd9db-cabf-4b92-a2a7-b3b9594b1e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/Enterprise-300x158.png 300w, http://3.145.59.133:8202/wp-content/uploads/2023/12/Enterprise-1024x538.png 1024w, http://3.145.59.133:8202/wp-content/uploads/2023/12/Enterprise-768x403.png 768w, http://3.145.59.133:8202/wp-content/uploads/2023/12/Enterprise.png 1200w</value>
      <webElementGuid>b0b94f1e-cc42-47fb-8540-886ffbc16d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>78fb7f1e-6eb5-43f7-8667-d4fc4e83a1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-213 page-child parent-pageid-203 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-213 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-213&quot;]/div[@class=&quot;elementor-element elementor-element-71ab9126 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-365d7baa elementor-grid-3 elementor-grid-tablet-2 elementor-grid-mobile-1 elementor-posts--thumbnail-top elementor-widget elementor-widget-posts&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-posts-container elementor-posts elementor-posts--skin-classic elementor-grid elementor-has-item-ratio&quot;]/article[@class=&quot;elementor-post elementor-grid-item post-457 post type-post status-publish format-standard has-post-thumbnail hentry category-accessibility-testing category-erp-testing category-mobile-testing category-performance-testing category-plato-panel-talks category-sap-testing category-test-automation&quot;]/a[@class=&quot;elementor-post__thumbnail__link&quot;]/div[@class=&quot;elementor-post__thumbnail elementor-fit-height&quot;]/img[@class=&quot;attachment-medium size-medium wp-image-460&quot;]</value>
      <webElementGuid>e893570a-61db-4362-b76a-8ce7f18f8a45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/Enterprise-300x158.png')]</value>
      <webElementGuid>1071ef9f-b0df-40f5-a413-c52a6dc5090f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>d98ec2f8-175f-4ccb-bc9f-28167181b6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/2023/12/Enterprise-300x158.png']</value>
      <webElementGuid>09156a42-b3aa-47fd-a457-321080e0d732</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
