<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_May 30, 2023_attachment-medium size-med_4e1550</name>
   <tag></tag>
   <elementGuidId>0744f7d4-ff94-4de3-a331-c21fc0c83d3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-medium.size-medium.wp-image-958</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/Panel-talk-accessibility5-300x169.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aea296ce-4bff-4eb2-97c9-d33f3874cabc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>1cf51b59-2110-4a83-889e-dceb5996d6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>8582237e-9084-4f43-a3ed-792e0c628950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>b9510594-46f3-4920-890d-0f719952ae85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>169</value>
      <webElementGuid>1382dff7-6314-4fc0-a2d1-05ed30d216a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/Panel-talk-accessibility5-300x169.png</value>
      <webElementGuid>f4335eb9-f2f4-44bf-9feb-062febb61ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-medium size-medium wp-image-958</value>
      <webElementGuid>6a4f0ddf-94cd-4b25-8e80-e22c284f5b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/Panel-talk-accessibility5-300x169.png 300w, http://3.145.59.133:8202/wp-content/uploads/2023/12/Panel-talk-accessibility5-1024x576.png 1024w, http://3.145.59.133:8202/wp-content/uploads/2023/12/Panel-talk-accessibility5-768x432.png 768w, http://3.145.59.133:8202/wp-content/uploads/2023/12/Panel-talk-accessibility5-1536x864.png 1536w, http://3.145.59.133:8202/wp-content/uploads/2023/12/Panel-talk-accessibility5.png 1920w</value>
      <webElementGuid>6f620e81-2faa-4763-9ef9-18db5fac6530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>5db76147-7537-4e17-8921-231c9d5621dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-213 page-child parent-pageid-203 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-213 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-213&quot;]/div[@class=&quot;elementor-element elementor-element-71ab9126 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-365d7baa elementor-grid-3 elementor-grid-tablet-2 elementor-grid-mobile-1 elementor-posts--thumbnail-top elementor-widget elementor-widget-posts&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-posts-container elementor-posts elementor-posts--skin-classic elementor-grid elementor-has-item-ratio&quot;]/article[@class=&quot;elementor-post elementor-grid-item post-957 post type-post status-publish format-standard has-post-thumbnail hentry category-accessibility-testing category-plato-panel-talks&quot;]/a[@class=&quot;elementor-post__thumbnail__link&quot;]/div[@class=&quot;elementor-post__thumbnail elementor-fit-height&quot;]/img[@class=&quot;attachment-medium size-medium wp-image-958&quot;]</value>
      <webElementGuid>39dc2cab-9465-44ab-b359-b16d13ce11a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/Panel-talk-accessibility5-300x169.png')]</value>
      <webElementGuid>277464aa-d01e-4cb0-a277-87fd92ad5a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[2]/a/div/img</value>
      <webElementGuid>a12b0c80-6d1b-4872-80ec-7158d2d1f888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/2023/12/Panel-talk-accessibility5-300x169.png']</value>
      <webElementGuid>225d9b98-c679-4934-a32e-c1e6d0a6e4bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
