<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Profile</name>
   <tag></tag>
   <elementGuidId>c4756458-dc70-4641-af84-ed65badc69c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.current.menu-top.menu-icon-users.menu-top-first.menu-top-last > div.wp-menu-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-users']/a/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>351ad676-f277-4a04-a68c-613065978799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-menu-name</value>
      <webElementGuid>1cbcfe39-ff7f-40a5-b65d-d7792d18e08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Profile</value>
      <webElementGuid>7880ea89-2791-4cf0-adc6-b11d6d275cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-users&quot;)/a[@class=&quot;current menu-top menu-icon-users menu-top-first menu-top-last&quot;]/div[@class=&quot;wp-menu-name&quot;]</value>
      <webElementGuid>a14db7ed-2ada-471d-b278-378e4201855c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-users']/a/div[3]</value>
      <webElementGuid>ccbe7304-cc22-4fb0-a1c2-ec8a4a717cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inbound Messages'])[1]/following::div[5]</value>
      <webElementGuid>1e7ca9f0-652f-4257-8415-d692bf4d6a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flamingo'])[1]/following::div[5]</value>
      <webElementGuid>b08f4bd9-adcc-4e88-85fa-cb1938e2c2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collapse menu'])[1]/preceding::div[1]</value>
      <webElementGuid>d48a2da6-610c-4172-9022-acb510216bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/preceding::div[1]</value>
      <webElementGuid>eb3a9ae9-0630-495f-8410-d926b2272b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Profile']/parent::*</value>
      <webElementGuid>e29a6942-15b3-478d-b56a-0c0fa359e415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/div[3]</value>
      <webElementGuid>094b3275-202d-47f7-9352-c0c29cfc4c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Profile' or . = 'Profile')]</value>
      <webElementGuid>fde19f5b-6e71-46b1-8c50-a43a7905af79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
