<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Learn more about Accessibility Testing__524573</name>
   <tag></tag>
   <elementGuidId>0d882f4c-05df-4626-b30c-e70bbcc6c46e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg.webp')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-full.size-full.wp-image-157</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(9) > div > div > .elementor-element > .elementor-widget-container > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>00695541-c830-455e-8986-b85f05300298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>e0b576b3-5277-4886-8746-b615b8cb34e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>df9027d7-b10a-40bc-b39a-c5caa187cda8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>2048</value>
      <webElementGuid>4a48c3dd-6f53-4a78-bcfb-a2f01449a5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1152</value>
      <webElementGuid>15e67ec3-69c5-42bc-aecd-991306a428a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg.webp</value>
      <webElementGuid>43288921-beda-4807-b46c-fd04dccd3278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-full size-full wp-image-157</value>
      <webElementGuid>ef827d91-5ea7-4bc6-b792-9bbaa57a4283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg.webp 2048w, http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg-300x169.webp 300w, http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg-1024x576.webp 1024w, http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg-768x432.webp 768w, http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg-1536x864.webp 1536w</value>
      <webElementGuid>90a97593-e9c3-4d15-8596-d00a4a0eba8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 2048px) 100vw, 2048px</value>
      <webElementGuid>1c7d2296-2493-4182-883c-726e5cf4aeff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-203 page-parent page-child parent-pageid-195 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-203 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-203&quot;]/div[@class=&quot;elementor-element elementor-element-dffff3f e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-4e3cfed e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-3317eb4 elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/a[1]/img[@class=&quot;attachment-full size-full wp-image-157&quot;]</value>
      <webElementGuid>6eeaa6f9-26e5-4385-ad26-7e36bf0f1a80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg.webp')]</value>
      <webElementGuid>f86164a3-b9f8-4103-8aff-358eb7286c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/a/img</value>
      <webElementGuid>98550225-d6c7-4a73-abe4-9653fd5d79f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg.webp']</value>
      <webElementGuid>dcad2b75-aa56-4b9b-8261-90de6e176ea0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
