<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Learn more about Accessibility Testing_attachment-full size-full wp-image-157</name>
   <tag></tag>
   <elementGuidId>f6e8e474-bd29-45e2-96f1-9193159f7d85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-full.size-full.wp-image-157</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg.webp')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(9) > div > div > .elementor-element > .elementor-widget-container > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3287600c-5cbd-4db6-9dc7-a667516fffe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>886bcc03-0cb2-4e5f-a8c6-245fe9d59dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>9275ad23-3d12-42cd-b7aa-662eee2af48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>2048</value>
      <webElementGuid>efe0dc5d-a32b-473b-9dd3-b62d3b963620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1152</value>
      <webElementGuid>d90ef313-5d8b-4c7a-884f-5e743e7aed13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg.webp</value>
      <webElementGuid>56de4266-f60e-4a54-a57c-bdb14db7b7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-full size-full wp-image-157</value>
      <webElementGuid>70fece81-0881-464b-9f97-faef46b43fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg.webp 2048w, http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg-300x169.webp 300w, http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg-1024x576.webp 1024w, http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg-768x432.webp 768w, http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg-1536x864.webp 1536w</value>
      <webElementGuid>0575b380-bac8-4e5e-bba0-8cb82a794d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 2048px) 100vw, 2048px</value>
      <webElementGuid>3a64f22c-0740-42aa-8b00-a5b12ca9bbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-203 page-parent page-child parent-pageid-195 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-203 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-203&quot;]/div[@class=&quot;elementor-element elementor-element-dffff3f e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-4e3cfed e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-3317eb4 elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/a[1]/img[@class=&quot;attachment-full size-full wp-image-157&quot;]</value>
      <webElementGuid>d0fcdf81-e110-4754-a7fe-0cba735e917b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg.webp')]</value>
      <webElementGuid>4772cb44-dfe5-4f3d-bfc2-0cf4d3b4bcb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/a/img</value>
      <webElementGuid>3ce8fb80-8256-4f38-aa45-1df64ea25358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg.webp']</value>
      <webElementGuid>334af800-27ef-4e9d-a618-07c0fb409f62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
