<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Learn more about Test Automation_attach_654f49</name>
   <tag></tag>
   <elementGuidId>9f5ac4cd-6d66-4483-8e62-ab5625a5d37f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A7320.png')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-full.size-full.wp-image-206</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(3) > div:nth-child(4) > div > div > .elementor-element > .elementor-widget-container > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>68450f00-ca67-4171-a494-a1a55ee5d9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>0b24ed43-3d3f-4613-86e3-d232e6dc5ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>893</value>
      <webElementGuid>1e1dade6-a105-41a1-913c-9574a471bbd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>605</value>
      <webElementGuid>34b29229-c6ca-4973-ac75-115741ddae4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A7320.png</value>
      <webElementGuid>2a2fe4ca-c77b-45c7-8621-064a50af9828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-full size-full wp-image-206</value>
      <webElementGuid>401b8a57-de39-4e0f-b734-124166422bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A7320.png 893w, http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A7320-300x203.png 300w, http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A7320-768x520.png 768w</value>
      <webElementGuid>b0cde784-fc68-4170-847d-f16bfac71f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 893px) 100vw, 893px</value>
      <webElementGuid>495e5f7d-70d2-4057-94e8-7370b65606ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-203 page-parent page-child parent-pageid-195 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-203 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-203&quot;]/div[@class=&quot;elementor-element elementor-element-c2ba6ba e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-53a509d e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-bd51ae5 elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/a[1]/img[@class=&quot;attachment-full size-full wp-image-206&quot;]</value>
      <webElementGuid>8d22c99a-56c9-4946-854e-62cb6560e6b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A7320.png')]</value>
      <webElementGuid>dab05d67-bb67-4507-8728-a33b0e90da26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/div/div/div/a/img</value>
      <webElementGuid>92ff423f-dfd9-4903-8dac-27381bc5d5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A7320.png']</value>
      <webElementGuid>42cfbca1-717d-4681-8261-a8645c775954</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
