<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LinkSubject1</name>
   <tag></tag>
   <elementGuidId>5ef28526-5c4e-4da4-8d81-e08efa4eb5e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='the-list']/tr/td/strong/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'http://3.145.59.133:8202/wp-admin/admin.php?page=flamingo_inbound&amp;post=1428&amp;action=edit' and (text() = '[your-subject]' or . = '[your-subject]')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>xpath=//tbody[@id='the-list']/tr/td/strong/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9ad23302-67b9-441b-85cc-0e28ecbe0fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row-title</value>
      <webElementGuid>b6eafa57-69ad-4e54-b074-761581ebfed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-admin/admin.php?page=flamingo_inbound&amp;post=1428&amp;action=edit</value>
      <webElementGuid>5413efc7-4278-4927-835a-01ca4f46a856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Edit “[your-subject]”</value>
      <webElementGuid>57f5e04c-f92e-4a9c-9c55-d9a2ee02f4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[your-subject]</value>
      <webElementGuid>748db9dc-d5e4-4027-8104-bbfb45d72526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;the-list&quot;)/tr[2]/td[@class=&quot;subject column-subject has-row-actions column-primary&quot;]/strong[1]/a[@class=&quot;row-title&quot;]</value>
      <webElementGuid>b02c6cd3-a34f-42b8-9a78-24db14cb4798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='the-list']/tr[2]/td/strong/a</value>
      <webElementGuid>02c6d5dd-348a-4d14-a958-a44bc0bf4900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'[your-subject]')])[2]</value>
      <webElementGuid>ed90209b-00ec-4a15-a1c7-6c01c9aca773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Training page - Application Form'])[1]/following::a[1]</value>
      <webElementGuid>b89caf39-278f-4cab-af61-129bf6e66c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Form 7'])[2]/following::a[2]</value>
      <webElementGuid>a3e2bfb7-9b95-4d80-8ad7-70dc30646597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[2]/preceding::a[1]</value>
      <webElementGuid>82e64795-b886-4915-b3f4-62aa221ccc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show more details'])[2]/preceding::a[2]</value>
      <webElementGuid>99408856-4014-49a4-92c7-e41dc3253095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://3.145.59.133:8202/wp-admin/admin.php?page=flamingo_inbound&amp;post=1428&amp;action=edit']</value>
      <webElementGuid>4d8b6c17-1a82-4387-8427-02d1423e58b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/strong/a</value>
      <webElementGuid>0312a861-c54b-49da-af1a-778465dd17bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://3.145.59.133:8202/wp-admin/admin.php?page=flamingo_inbound&amp;post=1428&amp;action=edit' and (text() = '[your-subject]' or . = '[your-subject]')]</value>
      <webElementGuid>f1c004b2-d848-4bff-a1b3-0004cf4cfbef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
