<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LinkView1</name>
   <tag></tag>
   <elementGuidId>ff923263-a7f5-465e-8be9-8f55ed39220a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.edit > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='the-list']/tr/td/div/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e7377860-e458-48c9-8ffb-cfa7f2878b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-admin/admin.php?page=flamingo_inbound&amp;post=1429&amp;action=edit</value>
      <webElementGuid>3fadf8c4-d70b-4afb-9dd7-897e532f3f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>e52ae677-05e0-4836-9282-f044dfc71480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;the-list&quot;)/tr[1]/td[@class=&quot;subject column-subject has-row-actions column-primary&quot;]/div[@class=&quot;row-actions visible&quot;]/span[@class=&quot;edit&quot;]/a[1]</value>
      <webElementGuid>44e97007-6a4d-4242-98d2-af49892228b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='the-list']/tr/td/div/span/a</value>
      <webElementGuid>74aa3bc4-c0f1-49f2-a5b9-94c5aed7966d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View')]</value>
      <webElementGuid>6b9f003e-2a66-4db8-be9f-6b2c8c997a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[your-subject]'])[1]/following::a[1]</value>
      <webElementGuid>5d2adeee-ea47-4429-9fd8-4d98efc1aa5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort descending.'])[1]/following::a[2]</value>
      <webElementGuid>6bc43b0a-8562-4868-a05f-b56d6ced1e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show more details'])[1]/preceding::a[1]</value>
      <webElementGuid>f2ace19d-1d67-49cf-ac8c-b28633b88586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Samuel &lt;[your-email]>'])[1]/preceding::a[1]</value>
      <webElementGuid>7b315a0a-be0c-4842-87b9-48932e7fa8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>4fb33abd-b4bd-4f43-95c4-24c20bf31ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://3.145.59.133:8202/wp-admin/admin.php?page=flamingo_inbound&amp;post=1429&amp;action=edit'])[2]</value>
      <webElementGuid>c8afdb73-6d98-4470-aacf-ebb9265eddad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/span/a</value>
      <webElementGuid>7537eaea-6163-4888-b0b2-4a7ef1a39e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://3.145.59.133:8202/wp-admin/admin.php?page=flamingo_inbound&amp;post=1429&amp;action=edit' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>3259a142-1133-4fbf-8eb2-9eadab7d0b22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
