<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Learn more about user acceptance testin_a3fa31</name>
   <tag></tag>
   <elementGuidId>e15e6902-0234-45b0-94a8-bcd4880185ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-medium.size-medium.wp-image-911</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/javier-trueba-vFJNeWJAA2g-unsplash-scaled-1-300x200.jpg')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>15e037b6-8957-467d-a213-2fc7e5784fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>6f938e51-fa6e-4771-8b40-253a7a36c505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>b51adbc8-6cdc-49d9-8c31-affef941e914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>c838a4b2-26db-4148-94e2-15e4b82d707b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/javier-trueba-vFJNeWJAA2g-unsplash-scaled-1-300x200.jpg</value>
      <webElementGuid>e3d8d365-bfa4-44c1-8977-759224c379f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-medium size-medium wp-image-911</value>
      <webElementGuid>2eff49b0-4656-41b9-81a1-d45dc39678b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/javier-trueba-vFJNeWJAA2g-unsplash-scaled-1-300x200.jpg 300w, http://3.145.59.133:8202/wp-content/uploads/2023/12/javier-trueba-vFJNeWJAA2g-unsplash-scaled-1-1024x683.jpg 1024w, http://3.145.59.133:8202/wp-content/uploads/2023/12/javier-trueba-vFJNeWJAA2g-unsplash-scaled-1-768x512.jpg 768w, http://3.145.59.133:8202/wp-content/uploads/2023/12/javier-trueba-vFJNeWJAA2g-unsplash-scaled-1-1536x1024.jpg 1536w, http://3.145.59.133:8202/wp-content/uploads/2023/12/javier-trueba-vFJNeWJAA2g-unsplash-scaled-1-2048x1366.jpg 2048w</value>
      <webElementGuid>ffb38343-88c9-4924-8af9-14d0fb159511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>bbb38806-3207-4b86-a97b-cf4c616918b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-220 page-child parent-pageid-203 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-220 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-220&quot;]/div[@class=&quot;elementor-element elementor-element-87cb1d7 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-506719af elementor-grid-3 elementor-grid-tablet-2 elementor-grid-mobile-1 elementor-posts--thumbnail-top elementor-widget elementor-widget-posts&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-posts-container elementor-posts elementor-posts--skin-classic elementor-grid elementor-has-item-ratio&quot;]/article[@class=&quot;elementor-post elementor-grid-item post-900 post type-post status-publish format-standard has-post-thumbnail hentry category-user-acceptance-testing-uat&quot;]/a[@class=&quot;elementor-post__thumbnail__link&quot;]/div[@class=&quot;elementor-post__thumbnail&quot;]/img[@class=&quot;attachment-medium size-medium wp-image-911&quot;]</value>
      <webElementGuid>0e048218-be64-4ae5-a192-6d06b9a7c9dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/javier-trueba-vFJNeWJAA2g-unsplash-scaled-1-300x200.jpg')]</value>
      <webElementGuid>66c1cf51-ba8c-4fee-906c-ec62e2a1d51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>9ca8da81-16ac-48c0-b1a5-624a7b75e2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/2023/12/javier-trueba-vFJNeWJAA2g-unsplash-scaled-1-300x200.jpg']</value>
      <webElementGuid>83bb7d5b-4feb-48de-bc27-7b5a973d630a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
