<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Identify and educate stakeholders_attac_91ecb5</name>
   <tag></tag>
   <elementGuidId>5657c0c0-a14f-4b5b-9507-334d72fad82f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.elementor-element.elementor-element-5583714.elementor-widget.elementor-widget-image > div.elementor-widget-container > img.attachment-medium.size-medium.wp-image-250</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/circle-check-solid-1.png')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4ec902e4-8f10-4765-9677-795b05196d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>e8adcc58-37f2-4750-b414-f70871362356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>74</value>
      <webElementGuid>6f6f4eeb-21e8-4489-a316-d2854e755571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>74</value>
      <webElementGuid>95d8ebe2-0327-4038-a79c-9d5682add3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/circle-check-solid-1.png</value>
      <webElementGuid>f3555004-dda1-486e-b0d5-6d237e7648ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-medium size-medium wp-image-250</value>
      <webElementGuid>028e1b2c-cc04-4359-a25b-3197c051eba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-220 page-child parent-pageid-203 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-220 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-220&quot;]/div[@class=&quot;elementor-element elementor-element-bf9d266 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-26ffa43 e-con-full e-grid e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-58d9945 e-flex e-con-boxed e-con e-child&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-5583714 elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[@class=&quot;attachment-medium size-medium wp-image-250&quot;]</value>
      <webElementGuid>6d69e71d-e3ba-41e0-8291-7841d43c23c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/circle-check-solid-1.png')])[2]</value>
      <webElementGuid>a54558be-a6ef-42a9-b9b0-b153601b227b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>d4827d4b-4e7b-43c1-b7a1-7fb59c170640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/2023/12/circle-check-solid-1.png']</value>
      <webElementGuid>f8769f93-e5f6-4181-a6c6-c5a637116ee4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
