<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Services_attachment-full size-full wp-i_a12d8c</name>
   <tag></tag>
   <elementGuidId>5b22f85a-853e-4fdc-a4d5-510e87d731af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A2388.png')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-full.size-full.wp-image-198</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.elementor-element > div > .elementor-element > .elementor-widget-container > a >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>47afa456-4d9c-4020-8b4b-7bdd8ed36094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>39889634-1f6f-434d-9bfe-5b7fa503a11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>893</value>
      <webElementGuid>014b3cad-2c60-44ef-9c40-b87f5ec7df74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>453</value>
      <webElementGuid>2c32e932-6a03-4f01-acdd-f2ac0efc634f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A2388.png</value>
      <webElementGuid>33b5845e-0aa5-4bf4-9e27-9e1557012633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-full size-full wp-image-198</value>
      <webElementGuid>66564f5f-3dc0-4d38-b983-0de6657e19f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A2388.png 893w, http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A2388-300x152.png 300w, http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A2388-768x390.png 768w</value>
      <webElementGuid>29012be6-2eae-4ef6-a38c-32d9159ec209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 893px) 100vw, 893px</value>
      <webElementGuid>a1b966bd-c3da-41ba-acae-03ee00009c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-195 page-parent wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-195 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-195&quot;]/div[@class=&quot;elementor-element elementor-element-3c28948 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-99a267d e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-87f23a4 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-c45b4bb elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/a[1]/img[@class=&quot;attachment-full size-full wp-image-198&quot;]</value>
      <webElementGuid>a17eaf0c-8ded-463c-9a80-2a6ae7f624db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A2388.png')]</value>
      <webElementGuid>76aa8fba-d367-4ec7-8d5d-cfe74598e348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/a/img</value>
      <webElementGuid>7818d4a3-263c-4b36-9aeb-bb02fd7f1d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A2388.png']</value>
      <webElementGuid>61dc3ec2-7206-4b13-b15d-c1973dadffcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
