<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Under 10,00010,001 - 50,00050,001 - _dcc881</name>
   <tag></tag>
   <elementGuidId>9c2c7dd1-f8ae-46b0-8127-2775023112c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'menu-559' and (text() = 'Under $10,000$10,001 - $50,000$50,001 - $250,000$250,000+Undetermined' or . = 'Under $10,000$10,001 - $50,000$50,001 - $250,000$250,000+Undetermined')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='menu-559']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;menu-559&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f09ab4d5-64de-4975-a2e0-f39122db3523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-select wpcf7-validates-as-required</value>
      <webElementGuid>75af8896-8da8-4b4d-a48f-223e0f6bd7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8207a510-2247-4f7c-bb0f-9f5e524c5b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6e749648-1aaa-49a2-af0a-42ad7008826d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu-559</value>
      <webElementGuid>90eae104-9193-4aee-94f8-db1cdf16e5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Under $10,000$10,001 - $50,000$50,001 - $250,000$250,000+Undetermined</value>
      <webElementGuid>1d661d5f-1e7e-456f-8922-564a8f9999a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f1107-p195-o1&quot;)/form[@class=&quot;wpcf7-form init&quot;]/div[@class=&quot;whole-form&quot;]/p[10]/span[@class=&quot;wpcf7-form-control-wrap&quot;]/select[@class=&quot;wpcf7-form-control wpcf7-select wpcf7-validates-as-required&quot;]</value>
      <webElementGuid>ec4ec86f-94fe-446b-bc86-3ccd02c4ca08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='menu-559']</value>
      <webElementGuid>8e17cef2-8ace-4a36-aa45-4731887bf18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f1107-p195-o1']/form/div[2]/p[10]/span/select</value>
      <webElementGuid>9a1231f1-fb79-4f37-bad3-4dadbfa6f71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::select[1]</value>
      <webElementGuid>7717f9f2-aae5-4b63-937c-ada454d61860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work With Us'])[7]/preceding::select[1]</value>
      <webElementGuid>179a9b37-b79f-49b9-b7b6-282f13abf456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GENERAL BUSINESS INQUIRIES'])[1]/preceding::select[1]</value>
      <webElementGuid>d1b90000-72fc-4c69-819c-3ff23c8737df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]/span/select</value>
      <webElementGuid>d46eb06d-4ee6-4614-b518-8beb8febd31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'menu-559' and (text() = 'Under $10,000$10,001 - $50,000$50,001 - $250,000$250,000+Undetermined' or . = 'Under $10,000$10,001 - $50,000$50,001 - $250,000$250,000+Undetermined')]</value>
      <webElementGuid>cb6eb7f3-9025-4884-9c66-71ef3d6a2f56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
