<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Immediately1-3 Months3-6 Months6 Months</name>
   <tag></tag>
   <elementGuidId>93162502-538c-4ef4-86d2-38c2baca23cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'menu-998']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='menu-998']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;menu-998&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu-998</value>
      <webElementGuid>893c5f81-8777-4fb8-a3fa-2333f8c2eaa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='menu-998']</value>
      <webElementGuid>daedd403-507f-4319-a817-e32bdad3abce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f1107-p195-o1']/form/div[2]/p[8]/span/select</value>
      <webElementGuid>a51d408b-9886-4b3e-9330-233f5c03f12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>916cbee5-6193-4350-91c0-217ef85a1e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/preceding::select[1]</value>
      <webElementGuid>b5458d39-09ae-472c-b937-39a19db648aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[8]/span/select</value>
      <webElementGuid>eaf539d3-2ea0-4a1d-b22e-d55db6163743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'menu-998' and (text() = 'Immediately1-3 Months3-6 Months6+ Months' or . = 'Immediately1-3 Months3-6 Months6+ Months')]</value>
      <webElementGuid>3c56e02c-2476-4e1f-af38-a431cb9eea29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
