<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Under 10,00010,001 - 50,00050,001 - _dcc881</name>
   <tag></tag>
   <elementGuidId>9c2c7dd1-f8ae-46b0-8127-2775023112c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'menu-559' and (text() = 'Under $10,000$10,001 - $50,000$50,001 - $250,000$250,000+Undetermined' or . = 'Under $10,000$10,001 - $50,000$50,001 - $250,000$250,000+Undetermined')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='menu-559']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;menu-559&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8709e928-0042-4d13-a405-b1ab037f8d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-select wpcf7-validates-as-required</value>
      <webElementGuid>3249e0d3-35e1-480f-80e4-3662ae130fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cf8e30ab-89d7-45cd-a990-f157df41ffc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cf1c906a-2684-44d3-b9cd-a21b02ed608a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu-559</value>
      <webElementGuid>aa72af61-910a-4597-b360-3c13e0998e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Under $10,000$10,001 - $50,000$50,001 - $250,000$250,000+Undetermined</value>
      <webElementGuid>cb04b59d-050f-4109-9927-3996b28d51b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f1107-p195-o1&quot;)/form[@class=&quot;wpcf7-form init&quot;]/div[@class=&quot;whole-form&quot;]/p[10]/span[@class=&quot;wpcf7-form-control-wrap&quot;]/select[@class=&quot;wpcf7-form-control wpcf7-select wpcf7-validates-as-required&quot;]</value>
      <webElementGuid>f5814dcf-e9cd-4fff-9fae-3ccfcaf89de5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='menu-559']</value>
      <webElementGuid>2100f2a3-fe45-4bf4-bd95-248b575c4fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f1107-p195-o1']/form/div[2]/p[10]/span/select</value>
      <webElementGuid>0de4b2d4-10e7-4616-9420-f3aaf1ceb134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::select[1]</value>
      <webElementGuid>b2e80fbb-c07f-43c7-a4d0-02de68768681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work With Us'])[7]/preceding::select[1]</value>
      <webElementGuid>0dedc50d-6e07-421d-aa59-1eecd3a6be3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GENERAL BUSINESS INQUIRIES'])[1]/preceding::select[1]</value>
      <webElementGuid>fa1d0788-665c-4f78-a310-28887bea413f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]/span/select</value>
      <webElementGuid>cb84e607-b6ce-4317-9cdc-0f8ea9ae1b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'menu-559' and (text() = 'Under $10,000$10,001 - $50,000$50,001 - $250,000$250,000+Undetermined' or . = 'Under $10,000$10,001 - $50,000$50,001 - $250,000$250,000+Undetermined')]</value>
      <webElementGuid>d4696042-9dfd-4ce1-880c-1eda607aedd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
