<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Under 10,00010,001 - 50,00050,001 - _dcc881</name>
   <tag></tag>
   <elementGuidId>9c2c7dd1-f8ae-46b0-8127-2775023112c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='menu-559']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;menu-559&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>23ceda3d-701e-4829-83f9-f5d4ecb2874a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-select wpcf7-validates-as-required</value>
      <webElementGuid>c8d0bb15-40a8-4f52-bc5a-2fb4362bc0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>db85527d-7410-4dea-8ae3-6afee4755a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>619cb6c6-23b6-4085-ae1f-355d386146a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu-559</value>
      <webElementGuid>03b565fe-276b-4a7c-a6a1-068a4617ef2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Under $10,000$10,001 - $50,000$50,001 - $250,000$250,000+Undetermined</value>
      <webElementGuid>38e2d39f-373f-4766-b939-267d65501644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f1107-p195-o1&quot;)/form[@class=&quot;wpcf7-form init&quot;]/div[@class=&quot;whole-form&quot;]/p[10]/span[@class=&quot;wpcf7-form-control-wrap&quot;]/select[@class=&quot;wpcf7-form-control wpcf7-select wpcf7-validates-as-required&quot;]</value>
      <webElementGuid>c3a9a54e-1b80-492d-8a08-98a7bf967a30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='menu-559']</value>
      <webElementGuid>966ad8dd-812b-413e-a381-61b10f215beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f1107-p195-o1']/form/div[2]/p[10]/span/select</value>
      <webElementGuid>3df0b482-242a-4276-b160-f37d483520ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::select[1]</value>
      <webElementGuid>253a0888-0ab5-49f2-9bd0-f55d08f3f27f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work With Us'])[7]/preceding::select[1]</value>
      <webElementGuid>6b88f046-c313-492b-bd1b-e01e8ff46f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GENERAL BUSINESS INQUIRIES'])[1]/preceding::select[1]</value>
      <webElementGuid>e71e19a9-b309-4d2b-9eff-69f7385daf3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]/span/select</value>
      <webElementGuid>a7e8b1ed-b8d5-44b8-a0cb-05a2b0ef82c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'menu-559' and (text() = 'Under $10,000$10,001 - $50,000$50,001 - $250,000$250,000+Undetermined' or . = 'Under $10,000$10,001 - $50,000$50,001 - $250,000$250,000+Undetermined')]</value>
      <webElementGuid>8a78e9fe-7383-4b81-887e-6f79b868ab98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
