<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Immediately1-3 Months3-6 Months6 Months</name>
   <tag></tag>
   <elementGuidId>93162502-538c-4ef4-86d2-38c2baca23cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;menu-998&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='menu-998']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>706b9c11-7aba-4318-bd17-eb4f01b0449b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-select wpcf7-validates-as-required</value>
      <webElementGuid>09205c16-c3bc-49f0-b818-2c90b53bd287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c32d2c67-f799-405e-b485-aea511b09ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>92010dc2-f5e6-4f46-821b-d48066423bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu-998</value>
      <webElementGuid>639405d2-5148-418c-b643-ddd1424c535d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Immediately1-3 Months3-6 Months6+ Months</value>
      <webElementGuid>7632707d-853b-46f6-96c0-361dca7c77e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f1107-p195-o1&quot;)/form[@class=&quot;wpcf7-form init&quot;]/div[@class=&quot;whole-form&quot;]/p[8]/span[@class=&quot;wpcf7-form-control-wrap&quot;]/select[@class=&quot;wpcf7-form-control wpcf7-select wpcf7-validates-as-required&quot;]</value>
      <webElementGuid>4012044a-f65f-458f-a65c-138613e03838</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='menu-998']</value>
      <webElementGuid>1afbe2a1-caa5-4f45-b733-fb001fe993c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f1107-p195-o1']/form/div[2]/p[8]/span/select</value>
      <webElementGuid>d3c76d99-6ccc-4a95-9872-783ba2d0ca58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>881b2d6c-34a7-4aeb-a8ee-b3804d7ebf0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/preceding::select[1]</value>
      <webElementGuid>328dcfbd-c32c-49b4-8e63-926414b7f736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[8]/span/select</value>
      <webElementGuid>7e4a91f1-9c25-4968-814c-888b37c89e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'menu-998' and (text() = 'Immediately1-3 Months3-6 Months6+ Months' or . = 'Immediately1-3 Months3-6 Months6+ Months')]</value>
      <webElementGuid>8318a3e8-23c7-43b2-9a2f-c3df01359fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
