<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CalgaryFrederictonHalifaxKamloopsMir_1c7d47</name>
   <tag></tag>
   <elementGuidId>28283947-a041-4745-a5e6-f8bde6f78028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='menu-471']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;menu-471&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>167a96f8-3464-4d25-9059-fe261096004c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-select wpcf7-validates-as-required</value>
      <webElementGuid>e1d99d20-b592-4554-992e-f253a909fe4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f278bc86-2ba4-4a79-bf07-ab5605c848d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bb78584f-1500-4580-9bfc-c51bff90ec10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu-471</value>
      <webElementGuid>5ee7719a-1a6b-4948-95e9-bf43fe1716bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CalgaryFrederictonHalifaxKamloopsMiramichiOttawaReginaSault Ste. MarieTorontoVancouverVictoriaGeneral (Not one of these locations)</value>
      <webElementGuid>7fc7e334-5262-4bdb-b5ad-f83ee0072411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f1107-p195-o1&quot;)/form[@class=&quot;wpcf7-form init&quot;]/div[@class=&quot;whole-form&quot;]/p[4]/span[@class=&quot;wpcf7-form-control-wrap&quot;]/select[@class=&quot;wpcf7-form-control wpcf7-select wpcf7-validates-as-required&quot;]</value>
      <webElementGuid>83031b46-7a85-4506-be25-e63e0fa24e91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='menu-471']</value>
      <webElementGuid>962670a1-3dcb-4714-993d-4946967847aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f1107-p195-o1']/form/div[2]/p[4]/span/select</value>
      <webElementGuid>a4f9aaef-3f1b-4804-8a4c-628ae4f6a01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>900ac5c0-676b-4c60-a14e-73142dd56cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[1]</value>
      <webElementGuid>a988f2d5-ff69-42ad-8547-e57bba0bfea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>8537a9be-7017-4c8a-82ba-7cde5ebdfed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'menu-471' and (text() = 'CalgaryFrederictonHalifaxKamloopsMiramichiOttawaReginaSault Ste. MarieTorontoVancouverVictoriaGeneral (Not one of these locations)' or . = 'CalgaryFrederictonHalifaxKamloopsMiramichiOttawaReginaSault Ste. MarieTorontoVancouverVictoriaGeneral (Not one of these locations)')]</value>
      <webElementGuid>0c7c3058-a4dd-4e40-9055-0e6aa4fe36cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
