<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Please fill out this field_1</name>
   <tag></tag>
   <elementGuidId>0b23eca0-ac64-4976-ad77-c95b9123ea03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.field-space2 > p:nth-of-type(2) > b > font > span.wpcf7-form-control-wrap > span.wpcf7-not-valid-tip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wpcf7-f1107-p195-o1']/form/div[2]/div/div[2]/p[2]/b/font/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4f9398eb-b758-4c63-a146-433e58167e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-not-valid-tip</value>
      <webElementGuid>9d9a1747-2d76-44aa-bf28-499fe1533cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a5896054-88fc-4a9c-92e5-8beaf26036fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please fill out this field.</value>
      <webElementGuid>f9c038b4-c59a-4b82-9ecf-c2eaaa6d33b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f1107-p195-o1&quot;)/form[@class=&quot;wpcf7-form invalid&quot;]/div[@class=&quot;whole-form&quot;]/div[@class=&quot;inline&quot;]/div[@class=&quot;field-space2&quot;]/p[2]/b[1]/font[1]/span[@class=&quot;wpcf7-form-control-wrap&quot;]/span[@class=&quot;wpcf7-not-valid-tip&quot;]</value>
      <webElementGuid>26111d46-d104-4c2e-91c8-0c5a7934ca50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f1107-p195-o1']/form/div[2]/div/div[2]/p[2]/b/font/span/span</value>
      <webElementGuid>a3e0d977-3393-4d3a-aa29-d949daa4b11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p[2]/b/font/span/span</value>
      <webElementGuid>06e2492b-254f-414f-afa9-f448517bb4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Please fill out this field.' or . = 'Please fill out this field.')]</value>
      <webElementGuid>82474eed-8fe2-4a83-ad38-29abb5475d41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
