<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Please enter a telephone number</name>
   <tag></tag>
   <elementGuidId>7bcc2ff1-0dec-4e24-9d1a-653750774f86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wpcf7-f1107-p195-o1']/form/div[2]/div[2]/div[2]/p[2]/b/font/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4850aab3-372b-4d4e-a42d-e7357924e614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-not-valid-tip</value>
      <webElementGuid>11261c3a-166f-49a3-ac97-7617259f4dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>49f3b9fb-f833-41a0-9759-51a40a2bfdf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter a telephone number.</value>
      <webElementGuid>63d2f06d-34f3-4a9b-8aab-12499945588d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f1107-p195-o1&quot;)/form[@class=&quot;wpcf7-form init&quot;]/div[@class=&quot;whole-form&quot;]/div[@class=&quot;inline&quot;]/div[@class=&quot;field-space2&quot;]/p[2]/b[1]/font[1]/span[@class=&quot;wpcf7-form-control-wrap&quot;]/span[@class=&quot;wpcf7-not-valid-tip&quot;]</value>
      <webElementGuid>081fdafe-2c8c-4572-aed6-ab9d3a4467d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f1107-p195-o1']/form/div[2]/div[2]/div[2]/p[2]/b/font/span/span</value>
      <webElementGuid>85d44cfe-da2b-4fbe-af00-5361f87864b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[1]/preceding::span[1]</value>
      <webElementGuid>bde0c9b2-485a-4d04-b964-e244255662f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/p[2]/b/font/span/span</value>
      <webElementGuid>957490a0-fb10-4d7c-a894-8235046e966c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Please enter a telephone number.' or . = 'Please enter a telephone number.')]</value>
      <webElementGuid>6930ac99-fc2b-4d05-a128-065789742920</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
