<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PageError</name>
   <tag></tag>
   <elementGuidId>2d3f0a0b-80bc-447d-8adf-66d0dbcf9b3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'One or more fields have an error. Please check and try again.' or . = 'One or more fields have an error. Please check and try again.')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.wpcf7-response-output</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'One or more fields have an error. Please check and try again.' or . = 'One or more fields have an error. Please check and try again.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>40e5e9b0-4d06-48af-9f7a-077b2e325165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-response-output</value>
      <webElementGuid>e9591400-ae30-47a2-afe2-f813f7ca5686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a2c3f985-18bc-46e6-bb60-006b988a0e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>One or more fields have an error. Please check and try again.</value>
      <webElementGuid>80ba3e0a-fd32-468d-b5b9-72830d1f03eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f1233-p222-o1&quot;)/form[@class=&quot;wpcf7-form invalid&quot;]/div[@class=&quot;wpcf7-response-output&quot;]</value>
      <webElementGuid>8fb53e24-431c-45e1-9a94-188156efc845</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f1233-p222-o1']/form/div[5]</value>
      <webElementGuid>a021ed07-baa2-48f0-adb8-99c6129aa212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::div[2]</value>
      <webElementGuid>65ff3c3c-832b-420f-8dd3-5988098cf990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locations'])[1]/preceding::div[4]</value>
      <webElementGuid>b4c8bf65-86b2-4470-bf03-682037cce8e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calgary'])[2]/preceding::div[8]</value>
      <webElementGuid>ddf53f02-4ec6-477e-8392-07d08f0be443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>647deb81-63ef-4740-8631-95b9a1111d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'One or more fields have an error. Please check and try again.' or . = 'One or more fields have an error. Please check and try again.')]</value>
      <webElementGuid>60d90fe0-089f-45d5-820b-d03995ff68a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
