<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Please fill out this field</name>
   <tag></tag>
   <elementGuidId>1d1785ef-b3b5-462e-a344-3b2a8ccd3fe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.field-space2 > p:nth-of-type(2) > b > font > span.wpcf7-form-control-wrap > span.wpcf7-not-valid-tip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wpcf7-f1233-p222-o1']/form/div[2]/div[2]/p[2]/b/font/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>42b85edc-4916-4406-9e16-4f5461545da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-not-valid-tip</value>
      <webElementGuid>b9f82bd7-9e0d-4d6b-a8f4-3347325f9e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0e460937-0298-4cc5-aa38-56cdba0bc855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please fill out this field.</value>
      <webElementGuid>949f80ce-5059-4334-81a8-2e0fae87ceb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f1233-p222-o1&quot;)/form[@class=&quot;wpcf7-form init&quot;]/div[@class=&quot;inline&quot;]/div[@class=&quot;field-space2&quot;]/p[2]/b[1]/font[1]/span[@class=&quot;wpcf7-form-control-wrap&quot;]/span[@class=&quot;wpcf7-not-valid-tip&quot;]</value>
      <webElementGuid>8719b1fa-d387-40a1-9a33-b27bcf2f4b55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f1233-p222-o1']/form/div[2]/div[2]/p[2]/b/font/span/span</value>
      <webElementGuid>d0d5773f-59a9-4732-b553-8495583aa6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p[2]/b/font/span/span</value>
      <webElementGuid>3c24a2c5-b7b6-48b8-90e2-b431275d7590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Please fill out this field.' or . = 'Please fill out this field.')]</value>
      <webElementGuid>1be72818-4dc8-4be0-a21a-b76109738154</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
