<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Time_attachment-medium size-medium wp-i_e7f76a</name>
   <tag></tag>
   <elementGuidId>16bdfec3-2166-403b-9af6-4266c148f834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/ERP-TESTING_CHALLENGES-2.jpg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-medium.size-medium.wp-image-248</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a75ac925-468a-437c-b0b4-aae05e3f32db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>56850fc0-c82d-4c81-bb31-3137fd7e76fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>7836c376-3afa-477a-b8fd-fcb41a4a8702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>4ae7732e-2f57-48e4-a4f9-0c0f1a517ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/ERP-TESTING_CHALLENGES-2.jpg</value>
      <webElementGuid>5b74a365-0760-4002-93a1-84f4568f402f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-medium size-medium wp-image-248</value>
      <webElementGuid>ddeb9612-8cff-47bc-8ec5-8743808dc03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/ERP-TESTING_CHALLENGES-2.jpg 301w, http://3.145.59.133:8202/wp-content/uploads/2023/12/ERP-TESTING_CHALLENGES-2-150x150.jpg 150w</value>
      <webElementGuid>ada932e7-6081-41db-ac78-406b0002b0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>c1a82803-6047-4483-9f5e-8057ebee3698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-215 page-child parent-pageid-203 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-215 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-215&quot;]/div[@class=&quot;elementor-element elementor-element-19d9b32 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-1109236 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-6fcc548 e-flex e-con-boxed e-con e-child&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-368f5a8 elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[@class=&quot;attachment-medium size-medium wp-image-248&quot;]</value>
      <webElementGuid>4efad255-0be1-4962-9054-a4de2e3e9121</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/ERP-TESTING_CHALLENGES-2.jpg')]</value>
      <webElementGuid>ea8e148c-0b20-4dc2-a2c6-22f3c0d951b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>9b6f8002-d099-4f67-bff0-e7549d61fb22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/2023/12/ERP-TESTING_CHALLENGES-2.jpg']</value>
      <webElementGuid>13787584-b6b5-4118-aff8-bc07abaa2475</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
