<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_February 19, 2021_attachment-medium siz_30eb9c</name>
   <tag></tag>
   <elementGuidId>66201522-a6ef-4de8-ba4f-e7d267cfbcb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/smallnetwork-300x200.jpg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-medium.size-medium.wp-image-564</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9c37b645-e505-400b-b8ee-618af8071884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>7dd11b77-3431-4bcb-a4f2-5f7979ca587d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>6caa1478-04ec-416b-a7c2-2f46fd09fa98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>0ef2f150-b454-4998-afe7-04774c17f735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/smallnetwork-300x200.jpg</value>
      <webElementGuid>00ccfcc8-e5da-4b6a-a1ae-c63423024d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-medium size-medium wp-image-564</value>
      <webElementGuid>66f210f9-2a27-4b7b-a370-04b14dc82b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/smallnetwork-300x200.jpg 300w, http://3.145.59.133:8202/wp-content/uploads/2023/12/smallnetwork-768x512.jpg 768w, http://3.145.59.133:8202/wp-content/uploads/2023/12/smallnetwork.jpg 1000w</value>
      <webElementGuid>e8f7eafc-2d75-47d1-af8e-125fb0c5b147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>d5d77566-32e2-4bf6-acee-f27b35992779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-216 page-child parent-pageid-203 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-216 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-216&quot;]/div[@class=&quot;elementor-element elementor-element-8dd6399 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-6c2d051 elementor-grid-3 elementor-grid-tablet-2 elementor-grid-mobile-1 elementor-posts--thumbnail-top elementor-widget elementor-widget-posts&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-posts-container elementor-posts elementor-posts--skin-classic elementor-grid elementor-has-item-ratio&quot;]/article[@class=&quot;elementor-post elementor-grid-item post-561 post type-post status-publish format-standard has-post-thumbnail hentry category-continuous-integration-ci category-continuous-testing category-devops category-functional-testing&quot;]/a[@class=&quot;elementor-post__thumbnail__link&quot;]/div[@class=&quot;elementor-post__thumbnail&quot;]/img[@class=&quot;attachment-medium size-medium wp-image-564&quot;]</value>
      <webElementGuid>2d5e03f3-9435-4169-b15a-2a9b89632b00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/smallnetwork-300x200.jpg')]</value>
      <webElementGuid>6ed0b346-efcf-4f62-9e2d-e90d64f4cbae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[2]/a/div/img</value>
      <webElementGuid>9a18e1dc-73e0-439a-99ac-ef2fd5155133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/2023/12/smallnetwork-300x200.jpg']</value>
      <webElementGuid>93943e12-dd5a-472f-bc90-1ae19631ffcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
