<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Work With Us_attachment-large size-large wp-image-158</name>
   <tag></tag>
   <elementGuidId>21220d5f-8ade-4e37-b364-9e76e690cf67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-large.size-large.wp-image-158</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/Group-76@2x-800x659-2.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;IT &amp; Business Consulting Home / IT &amp; Business Consulting Our network of quality &quot;i >> img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c774aef0-446e-4fc2-95b6-49dfe37b2e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>6109ac40-12ec-4bcb-bcb6-718a9fe90728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>7714cad9-f28a-4343-82d4-08c1a2687543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>659</value>
      <webElementGuid>94776ca2-2511-4d3c-b3c3-d329b01eae3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/Group-76@2x-800x659-2.png</value>
      <webElementGuid>c0ebec1b-1183-42d2-95d9-1ed82452eee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large wp-image-158</value>
      <webElementGuid>1c112169-8433-4a31-88d4-65f063f4dee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/Group-76@2x-800x659-2.png 800w, http://3.145.59.133:8202/wp-content/uploads/2023/12/Group-76@2x-800x659-2-300x247.png 300w, http://3.145.59.133:8202/wp-content/uploads/2023/12/Group-76@2x-800x659-2-768x633.png 768w</value>
      <webElementGuid>f2473b55-7e60-4a19-8b26-d6bf6fcff5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 800px) 100vw, 800px</value>
      <webElementGuid>eac84193-b82e-4a92-9976-5de884ea0b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-176 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-176 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-176&quot;]/div[@class=&quot;elementor-element elementor-element-9f8e5e8 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-a65b0d8 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-272fe66 elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[@class=&quot;attachment-large size-large wp-image-158&quot;]</value>
      <webElementGuid>e779bd08-b433-4293-9849-c037dd60d135</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/Group-76@2x-800x659-2.png')]</value>
      <webElementGuid>049a9305-9e00-403d-9e34-ea4fbf60bb49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>5671e691-0002-4ca8-8d61-e4da684d4790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/2023/12/Group-76@2x-800x659-2.png']</value>
      <webElementGuid>767beb81-45e8-4a89-9c17-dbb4a1fef5f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
