<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Learn more about Accessibility Testing_attachment-full size-full wp-image-157</name>
   <tag></tag>
   <elementGuidId>f6e8e474-bd29-45e2-96f1-9193159f7d85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-full.size-full.wp-image-157</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg.webp')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(9) > div > div > .elementor-element > .elementor-widget-container > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c3cd50f6-47a5-4a0d-a965-bfe3e4be1cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>60854ff3-a61d-4913-a3a5-37b7723aaf2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>3b54e42c-c20a-40fd-8527-a63e85b65cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>2048</value>
      <webElementGuid>dd416127-db93-4bbe-8149-8b10ae2d0dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1152</value>
      <webElementGuid>5a81aa5d-c237-4472-90ac-8d8e953a0697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg.webp</value>
      <webElementGuid>88b539b6-4281-4eef-b31b-c6722716c703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-full size-full wp-image-157</value>
      <webElementGuid>8284bf2c-cb5b-4bad-9452-918e0e5f3b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg.webp 2048w, http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg-300x169.webp 300w, http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg-1024x576.webp 1024w, http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg-768x432.webp 768w, http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg-1536x864.webp 1536w</value>
      <webElementGuid>27e05fcf-c37b-4381-9064-7a844867cb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 2048px) 100vw, 2048px</value>
      <webElementGuid>e7ca62d5-3ed8-491f-95ca-63156e30981a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-203 page-parent page-child parent-pageid-195 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-203 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-203&quot;]/div[@class=&quot;elementor-element elementor-element-dffff3f e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-4e3cfed e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-3317eb4 elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/a[1]/img[@class=&quot;attachment-full size-full wp-image-157&quot;]</value>
      <webElementGuid>cd6c63b8-98c6-42c8-88ec-ac1638548688</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg.webp')]</value>
      <webElementGuid>1ea38790-3782-446d-a5b9-5c03fb646089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/a/img</value>
      <webElementGuid>57580067-dd4e-4427-b91e-8105a5e87a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/2023/12/PLATO-Freddy-jpg.webp']</value>
      <webElementGuid>d62a4967-a769-4427-bd91-6ddca856931d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
