<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Testing Services_attachment-full size-f_0b10c3</name>
   <tag></tag>
   <elementGuidId>7ad2688b-b928-4b82-88b0-f9a410148700</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-full.size-full.wp-image-25</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A7346-800x541-1.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(3) > div:nth-child(3) > div > div > .elementor-element > .elementor-widget-container > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ce421c1a-3844-4456-9442-185d05e3fb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>0232f5fa-a68f-44e2-b3c2-87cb25e8b98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>db2ffe23-b306-462f-a1dc-9566120214b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>541</value>
      <webElementGuid>09d1eee4-bf5a-43f6-b922-e5c690c04008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A7346-800x541-1.png</value>
      <webElementGuid>17581a85-5b18-47a0-bace-0b23cb9cd47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-full size-full wp-image-25</value>
      <webElementGuid>bc61dd03-b6f3-4f23-b689-854daee38f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A7346-800x541-1.png 800w, http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A7346-800x541-1-300x203.png 300w, http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A7346-800x541-1-768x519.png 768w</value>
      <webElementGuid>c9bf5971-45b9-4da0-ac70-efe752266c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 800px) 100vw, 800px</value>
      <webElementGuid>4c847afa-d6a3-4dea-809b-bb2fc89f1f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-203 page-parent page-child parent-pageid-195 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-203 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-203&quot;]/div[@class=&quot;elementor-element elementor-element-e704e7f e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-eb03aea e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-ac64594 elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/a[1]/img[@class=&quot;attachment-full size-full wp-image-25&quot;]</value>
      <webElementGuid>020c35e7-9834-46f2-b25d-f1aef7070257</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A7346-800x541-1.png')]</value>
      <webElementGuid>fa8fceeb-5ef8-471d-b62f-c99be369eb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/div/a/img</value>
      <webElementGuid>42b9dfdd-1d2e-480c-a3c0-2b9be6a7ffbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/2023/12/D2A7346-800x541-1.png']</value>
      <webElementGuid>746fcee9-5918-4677-b03d-1ffa3b3aafac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
