<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>3da46320-77a7-4de1-80f1-98907b893547</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;MicrosoftTeams-image-10-400x271-1.png&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='MicrosoftTeams-image-10-400x271-1.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1e4f584c-06bb-43d4-b83a-620e18f5a3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>1f72d8d3-d79a-44dc-a1c5-771994641ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/elementor/thumbs/MicrosoftTeams-image-10-400x271-1-qwylmwtod6wm9qp05upm7asd2quggroan675kfo7o0.png</value>
      <webElementGuid>584255db-ea5e-440d-a688-9a94d58a80e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>MicrosoftTeams-image-10-400×271-1.png</value>
      <webElementGuid>a57f6673-0797-4422-92a0-48ac339c668b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>MicrosoftTeams-image-10-400x271-1.png</value>
      <webElementGuid>cbfb9fde-2116-44f6-8d17-d824e95cb181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>868c2891-7204-4c0e-81d5-6371ae2d7f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-219 page-child parent-pageid-203 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-219 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-219&quot;]/div[@class=&quot;elementor-element elementor-element-afb7ad3 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-5fdaa95 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-44a9c48 e-flex e-con-boxed e-con e-child&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-7c8ad6c elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[1]</value>
      <webElementGuid>26a6dd50-32b5-4eb9-9054-212a0e5cf465</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='MicrosoftTeams-image-10-400x271-1.png']</value>
      <webElementGuid>b0da2253-1f79-41f3-a375-c40ac6bd6f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/div/div/div/img</value>
      <webElementGuid>634a3fa4-03fe-4729-888f-5a7832742c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/elementor/thumbs/MicrosoftTeams-image-10-400x271-1-qwylmwtod6wm9qp05upm7asd2quggroan675kfo7o0.png' and @title = 'MicrosoftTeams-image-10-400×271-1.png' and @alt = 'MicrosoftTeams-image-10-400x271-1.png']</value>
      <webElementGuid>3fced59e-3f82-452a-9d18-7ed795b3ffc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
