<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e221e0d6-4140-48e3-b567-88d1dee40e25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;MicrosoftTeams-image-10-400x271-1.png&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='MicrosoftTeams-image-10-400x271-1.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c9c11f19-fa14-47db-86a3-1c5dbec19f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>94a2558b-f755-4f1f-821f-f55187857af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/elementor/thumbs/MicrosoftTeams-image-10-400x271-1-qwylmwtod6wm9qp05upm7asd2quggroan675kfo7o0.png</value>
      <webElementGuid>1092dc5d-6644-4c2e-9249-7616ea635b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>MicrosoftTeams-image-10-400×271-1.png</value>
      <webElementGuid>fc39629e-2b60-4486-af2b-4afb5a646800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>MicrosoftTeams-image-10-400x271-1.png</value>
      <webElementGuid>92669afc-558a-46ec-8f34-2ae7ffbd9b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>6663c94a-077f-44e4-a330-eaa278a8cee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-214 page-child parent-pageid-203 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-214 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-214&quot;]/div[@class=&quot;elementor-element elementor-element-5e2db85 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-318ee13 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-2b3b110 e-flex e-con-boxed e-con e-child&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-c8c7cba elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[1]</value>
      <webElementGuid>4bc64a1b-b358-40c1-90ea-adaae9f2ea32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='MicrosoftTeams-image-10-400x271-1.png']</value>
      <webElementGuid>ae1a0aa2-fa29-418c-9a9a-bb3a517650da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/div/div/img</value>
      <webElementGuid>606b34ee-2724-4e38-a832-a91bf6579e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/elementor/thumbs/MicrosoftTeams-image-10-400x271-1-qwylmwtod6wm9qp05upm7asd2quggroan675kfo7o0.png' and @title = 'MicrosoftTeams-image-10-400×271-1.png' and @alt = 'MicrosoftTeams-image-10-400x271-1.png']</value>
      <webElementGuid>f4901d9a-fce0-4245-ac95-8fd67d5e776e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
