<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>2ee95b5a-ae2d-4772-9cb2-12f90d61bfef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;D2A7275-400x271-1.png&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='D2A7275-400x271-1.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>34736846-cbe2-4f56-b866-44244db6abab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>2840af9c-fc9b-46da-a6c5-c60e6ddf7f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/elementor/thumbs/D2A7275-400x271-1-qwylmwtod6wm9qp05upm7asd2quggroan675kfo7o0.png</value>
      <webElementGuid>b1451e15-ae94-4322-9343-3733b90f502d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>D2A7275-400×271-1.png</value>
      <webElementGuid>b4f58963-1a90-483a-8e48-e5b8466adbca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>D2A7275-400x271-1.png</value>
      <webElementGuid>1b57f66d-6410-47d4-bac8-70f1cdf64ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>936c0bc5-d7ac-4444-8586-9c584305f4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-214 page-child parent-pageid-203 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-214 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-214&quot;]/div[@class=&quot;elementor-element elementor-element-5e2db85 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-318ee13 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-a3d3328 e-flex e-con-boxed e-con e-child&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-0156f9f elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[1]</value>
      <webElementGuid>8b5e47b0-9596-4935-9e0e-a808a28ea752</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='D2A7275-400x271-1.png']</value>
      <webElementGuid>3baae09c-b0e6-4031-85a5-a58e9de7cfcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div[2]/div/div/div/img</value>
      <webElementGuid>7f6bf6b1-cdac-4cbc-aa66-1bacf11ba5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/elementor/thumbs/D2A7275-400x271-1-qwylmwtod6wm9qp05upm7asd2quggroan675kfo7o0.png' and @title = 'D2A7275-400×271-1.png' and @alt = 'D2A7275-400x271-1.png']</value>
      <webElementGuid>0429f63a-17cf-49b8-b20a-0c2d3e9e9d60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
