<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>82e04291-c41b-486c-b4c7-6b480fc4f5ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;D2A2657-1.png&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='D2A2657-1.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4296f15b-6984-4aab-923a-fb86618f556f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>2b63d9a0-4dce-4c46-b1d4-2d15647766b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://3.145.59.133:8202/wp-content/uploads/elementor/thumbs/D2A2657-1-qwylmwtod6wm9qp05upm7asd2quggroan675kfo7o0.png</value>
      <webElementGuid>9b900d9f-d4ea-4398-b2c5-e7ed7d6010dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>D2A2657-1.png</value>
      <webElementGuid>788924b6-3c9d-497f-a8e1-653737a428d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>D2A2657-1.png</value>
      <webElementGuid>b3d22775-3d53-49c3-b74b-f3249e7c3204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>f4a7bc71-7119-4ec8-9905-7e7b9c5986a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-214 page-child parent-pageid-203 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-214 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-214&quot;]/div[@class=&quot;elementor-element elementor-element-5e2db85 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-318ee13 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-c1a1317 e-flex e-con-boxed e-con e-child&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-5a50411 elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[1]</value>
      <webElementGuid>d9b106ff-35b4-41e0-b1f3-440d79897149</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='D2A2657-1.png']</value>
      <webElementGuid>aa744c0d-8cc7-42ff-b319-3b03ea740a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/div/img</value>
      <webElementGuid>1e4d9f35-f9ee-4bb5-a57c-9e6c9311b17e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://3.145.59.133:8202/wp-content/uploads/elementor/thumbs/D2A2657-1-qwylmwtod6wm9qp05upm7asd2quggroan675kfo7o0.png' and @title = 'D2A2657-1.png' and @alt = 'D2A2657-1.png']</value>
      <webElementGuid>48265dff-639e-4206-b3a4-cdc526d918f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
